"""
A collection of all the values that the categorical columns may hold. This is based on a `value_counts` output and some regex magic.
Probably a data-drive approach would be nicer. But I'm in a hurry ;-)
"""


def get_categories():
    return [["Private",
             "Self-emp-not-inc",
             "Local-gov",
             "State-gov",
             "Self-emp-inc",
             "Federal-gov",
             "Without-pay",
             "Never-worked",
             "unknown"],

            ["HS-grad",
             "Some-college",
             "Bachelors",
             "Masters",
             "Assoc-voc",
             "th",
             "Assoc-acdm",
             "th",
             "th-th",
             "Prof-school",
             "th",
             "th",
             "Doctorate",
             "th-th",
             "st-th",
             "Preschool",
             "unknown"],

            ["Married-civ-spouse",
             "Never-married",
             "Divorced",
             "Separated",
             "Widowed",
             "Married-spouse-absent",
             "Married-AF-spouse",
             "unknown"],

            ["Prof-specialty",
             "Craft-repair",
             "Exec-managerial",
             "Adm-clerical",
             "Sales",
             "Other-service",
             "Machine-op-inspct",
             "Transport-moving",
             "Handlers-cleaners",
             "Farming-fishing",
             "Tech-support",
             "Protective-serv",
             "Priv-house-serv",
             "Armed-Forces",
             "unknown"],

            ["Husband",
             "Not-in-family",
             "Own-child",
             "Unmarried",
             "Wife",
             "Other-relative",
             "unknown"],

            ["White",
             "Black",
             "Asian-Pac-Islander",
             "Amer-Indian-Eskimo",
             "Other",
             "unknown"],

            ["Male",
             "Female",
             "unknown"],

            ["United-States",
             "Mexico",
             "Philippines",
             "Germany",
             "Canada",
             "Puerto-Rico",
             "El-Salvador",
             "India",
             "Cuba",
             "England",
             "Jamaica",
             "South",
             "China",
             "Italy",
             "Dominican-Republic",
             "Vietnam",
             "Guatemala",
             "Japan",
             "Poland",
             "Columbia",
             "Taiwan",
             "Haiti",
             "Iran",
             "Portugal",
             "Nicaragua",
             "Peru",
             "Greece",
             "France",
             "Ecuador",
             "Ireland",
             "Hong",
             "Trinadad&Tobago",
             "Cambodia",
             "Laos",
             "Thailand",
             "Yugoslavia",
             "Outlying-US(Guam-USVI-etc)",
             "Hungary",
             "Honduras",
             "Scotland",
             "Holand-Netherlands"
             "unknown"],
            ]
